/* Generated by Yosys 0.68 (git sha1 38e001a6f, Release, GNU /usr/bin/c++ 13.3.0) */

module branch_gshare(clk, rst, PC, branch, pred);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input [9:0] PC;
  wire [9:0] PC;
  input branch;
  wire branch;
  output pred;
  wire pred;
  wire [9:0] \$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_ADDR[9:0]$5 ;
  wire [7:0] \$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_DATA[7:0]$6 ;
  wire \$abc$1389$auto$mem.cc:1168:emulate_transparency$103[0] ;
  wire \$abc$1389$auto$mem.cc:1168:emulate_transparency$103[1] ;
  wire \$abc$1389$auto$mem.cc:1185:emulate_transparency$107[0] ;
  wire \$abc$1389$auto$mem.cc:1185:emulate_transparency$107[1] ;
  wire \$abc$1389$auto$mem.cc:1185:emulate_transparency$107[2] ;
  wire \$abc$1389$auto$mem.cc:1185:emulate_transparency$107[3] ;
  wire \$abc$1389$auto$mem.cc:1185:emulate_transparency$107[4] ;
  wire \$abc$1389$auto$mem.cc:1185:emulate_transparency$107[5] ;
  wire \$abc$1389$auto$mem.cc:1185:emulate_transparency$107[6] ;
  wire \$abc$1389$auto$mem.cc:1185:emulate_transparency$107[7] ;
  wire \$abc$1389$auto$mem.cc:1195:emulate_transparency$110 ;
  wire \$abc$1389$auto$mem.cc:1541:emulate_reset$99 ;
  wire \$abc$1389$auto$mem.cc:1643:emulate_read_first$94[0] ;
  wire \$abc$1389$auto$mem.cc:1643:emulate_read_first$94[1] ;
  wire \$abc$1389$auto$mem.cc:1643:emulate_read_first$94[2] ;
  wire \$abc$1389$auto$mem.cc:1643:emulate_read_first$94[3] ;
  wire \$abc$1389$auto$mem.cc:1643:emulate_read_first$94[4] ;
  wire \$abc$1389$auto$mem.cc:1643:emulate_read_first$94[5] ;
  wire \$abc$1389$auto$mem.cc:1643:emulate_read_first$94[6] ;
  wire \$abc$1389$auto$mem.cc:1643:emulate_read_first$94[7] ;
  wire \$abc$1389$auto$mem.cc:1643:emulate_read_first$94[8] ;
  wire \$abc$1389$auto$mem.cc:1643:emulate_read_first$94[9] ;
  wire \$abc$1389$auto$mem.cc:1645:emulate_read_first$95 ;
  wire \$abc$1389$auto$rtlil.cc:3314:And$109 ;
  wire \$abc$1389$auto$rtlil.cc:3513:MuxGate$1364 ;
  wire \$abc$1389$auto$rtlil.cc:3513:MuxGate$1366 ;
  wire \$abc$1389$auto$rtlil.cc:3513:MuxGate$1368 ;
  wire \$abc$1389$auto$rtlil.cc:3513:MuxGate$1370 ;
  wire \$abc$1389$auto$rtlil.cc:3513:MuxGate$1372 ;
  wire \$abc$1389$auto$rtlil.cc:3513:MuxGate$1374 ;
  wire \$abc$1389$auto$rtlil.cc:3513:MuxGate$1376 ;
  wire \$abc$1389$auto$rtlil.cc:3513:MuxGate$1378 ;
  wire \$abc$1389$auto$rtlil.cc:3513:MuxGate$1380 ;
  wire \$abc$1389$auto$rtlil.cc:3513:MuxGate$1382 ;
  wire \$abc$1389$auto$rtlil.cc:3513:MuxGate$1384 ;
  wire \$abc$1389$auto$rtlil.cc:3513:MuxGate$1386 ;
  wire \$abc$1389$new_n101 ;
  wire \$abc$1389$new_n102 ;
  wire \$abc$1389$new_n103 ;
  wire \$abc$1389$new_n104 ;
  wire \$abc$1389$new_n105 ;
  wire \$abc$1389$new_n106 ;
  wire \$abc$1389$new_n107 ;
  wire \$abc$1389$new_n108 ;
  wire \$abc$1389$new_n109 ;
  wire \$abc$1389$new_n110 ;
  wire \$abc$1389$new_n111 ;
  wire \$abc$1389$new_n112 ;
  wire \$abc$1389$new_n114 ;
  wire \$abc$1389$new_n117 ;
  wire \$abc$1389$new_n118 ;
  wire \$abc$1389$new_n119 ;
  wire \$abc$1389$new_n120 ;
  wire \$abc$1389$new_n121 ;
  wire \$abc$1389$new_n122 ;
  wire \$abc$1389$new_n123 ;
  wire \$abc$1389$new_n78 ;
  wire \$abc$1389$new_n79 ;
  wire \$abc$1389$new_n80 ;
  wire \$abc$1389$new_n81 ;
  wire \$abc$1389$new_n82 ;
  wire \$abc$1389$new_n83 ;
  wire \$abc$1389$new_n84 ;
  wire \$abc$1389$new_n85 ;
  wire \$abc$1389$new_n86 ;
  wire \$abc$1389$new_n87 ;
  wire \$abc$1389$new_n96 ;
  wire \$abc$1389$techmap\PHT.0.0.$not$memory_map.v:20$116_Y ;
  wire [7:0] \$auto$mem.cc:1642:emulate_read_first$93 ;
  wire [7:0] \$auto$memory_libmap.cc:1986:emit_port$113 ;
  wire [0:0] \$shiftx$pipelined_ext/branch_gshare/branch_gshare.sv:94$15.Y ;
  wire [9:0] GHR;
  wire [9:0] GHR_comb;
  wire [7:0] next_path;
  wire pred_reg;
  wire [9:0] table_index;
  wire [9:0] table_index_reg;
  sky130_fd_sc_hd__clkinv_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1390  (
    .A(table_index_reg[1]),
    .Y(\$abc$1389$new_n78 )
  );
  sky130_fd_sc_hd__clkinv_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1391  (
    .A(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[8] ),
    .Y(\$abc$1389$new_n79 )
  );
  sky130_fd_sc_hd__clkinv_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1392  (
    .A(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[7] ),
    .Y(\$abc$1389$new_n80 )
  );
  sky130_fd_sc_hd__clkinv_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1393  (
    .A(table_index_reg[6]),
    .Y(\$abc$1389$new_n81 )
  );
  sky130_fd_sc_hd__clkinv_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1394  (
    .A(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[5] ),
    .Y(\$abc$1389$new_n82 )
  );
  sky130_fd_sc_hd__clkinv_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1395  (
    .A(table_index_reg[4]),
    .Y(\$abc$1389$new_n83 )
  );
  sky130_fd_sc_hd__clkinv_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1396  (
    .A(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[2] ),
    .Y(\$abc$1389$new_n84 )
  );
  sky130_fd_sc_hd__clkinv_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1397  (
    .A(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[0] ),
    .Y(\$abc$1389$new_n85 )
  );
  sky130_fd_sc_hd__clkinv_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1398  (
    .A(table_index_reg[9]),
    .Y(\$abc$1389$new_n86 )
  );
  sky130_fd_sc_hd__clkinv_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1399  (
    .A(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[9] ),
    .Y(\$abc$1389$new_n87 )
  );
  sky130_fd_sc_hd__clkinv_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1400  (
    .A(\$abc$1389$auto$mem.cc:1645:emulate_read_first$95 ),
    .Y(\$abc$1389$techmap\PHT.0.0.$not$memory_map.v:20$116_Y )
  );
  sky130_fd_sc_hd__and2_0 \$abc$1389$auto$blifparse.cc:397:parse_blif$1401  (
    .A(PC[6]),
    .B(rst),
    .X(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_ADDR[9:0]$5 [6])
  );
  sky130_fd_sc_hd__and2_0 \$abc$1389$auto$blifparse.cc:397:parse_blif$1402  (
    .A(rst),
    .B(PC[2]),
    .X(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_ADDR[9:0]$5 [2])
  );
  sky130_fd_sc_hd__and2_0 \$abc$1389$auto$blifparse.cc:397:parse_blif$1403  (
    .A(rst),
    .B(PC[5]),
    .X(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_ADDR[9:0]$5 [5])
  );
  sky130_fd_sc_hd__and2_0 \$abc$1389$auto$blifparse.cc:397:parse_blif$1404  (
    .A(rst),
    .B(PC[4]),
    .X(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_ADDR[9:0]$5 [4])
  );
  sky130_fd_sc_hd__and2_0 \$abc$1389$auto$blifparse.cc:397:parse_blif$1405  (
    .A(rst),
    .B(PC[3]),
    .X(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_ADDR[9:0]$5 [3])
  );
  sky130_fd_sc_hd__and2_0 \$abc$1389$auto$blifparse.cc:397:parse_blif$1406  (
    .A(rst),
    .B(PC[1]),
    .X(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_ADDR[9:0]$5 [1])
  );
  sky130_fd_sc_hd__and2_0 \$abc$1389$auto$blifparse.cc:397:parse_blif$1407  (
    .A(rst),
    .B(PC[0]),
    .X(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_ADDR[9:0]$5 [0])
  );
  sky130_fd_sc_hd__nand2_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1408  (
    .A(rst),
    .B(branch),
    .Y(\$abc$1389$new_n96 )
  );
  sky130_fd_sc_hd__and3_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1409  (
    .A(rst),
    .B(branch),
    .C(next_path[0]),
    .X(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_DATA[7:0]$6 [1])
  );
  sky130_fd_sc_hd__and2_0 \$abc$1389$auto$blifparse.cc:397:parse_blif$1410  (
    .A(rst),
    .B(PC[8]),
    .X(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1364 )
  );
  sky130_fd_sc_hd__and2_0 \$abc$1389$auto$blifparse.cc:397:parse_blif$1411  (
    .A(rst),
    .B(PC[7]),
    .X(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1366 )
  );
  sky130_fd_sc_hd__nor2_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1412  (
    .A(next_path[0]),
    .B(\$abc$1389$new_n96 ),
    .Y(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_DATA[7:0]$6 [0])
  );
  sky130_fd_sc_hd__o21ai_0 \$abc$1389$auto$blifparse.cc:397:parse_blif$1413  (
    .A1(table_index_reg[0]),
    .A2(\$abc$1389$new_n85 ),
    .B1(\$abc$1389$auto$mem.cc:1645:emulate_read_first$95 ),
    .Y(\$abc$1389$new_n101 )
  );
  sky130_fd_sc_hd__o22ai_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1414  (
    .A1(table_index_reg[7]),
    .A2(\$abc$1389$new_n80 ),
    .B1(\$abc$1389$new_n81 ),
    .B2(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[6] ),
    .Y(\$abc$1389$new_n102 )
  );
  sky130_fd_sc_hd__o2bb2ai_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1415  (
    .A1_N(\$abc$1389$new_n81 ),
    .A2_N(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[6] ),
    .B1(table_index_reg[2]),
    .B2(\$abc$1389$new_n84 ),
    .Y(\$abc$1389$new_n103 )
  );
  sky130_fd_sc_hd__nor3_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1416  (
    .A(\$abc$1389$new_n101 ),
    .B(\$abc$1389$new_n102 ),
    .C(\$abc$1389$new_n103 ),
    .Y(\$abc$1389$new_n104 )
  );
  sky130_fd_sc_hd__o2bb2ai_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1417  (
    .A1_N(table_index_reg[7]),
    .A2_N(\$abc$1389$new_n80 ),
    .B1(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[1] ),
    .B2(\$abc$1389$new_n78 ),
    .Y(\$abc$1389$new_n105 )
  );
  sky130_fd_sc_hd__a22o_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1418  (
    .A1(\$abc$1389$new_n78 ),
    .A2(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[1] ),
    .B1(\$abc$1389$new_n85 ),
    .B2(table_index_reg[0]),
    .X(\$abc$1389$new_n106 )
  );
  sky130_fd_sc_hd__xor2_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1419  (
    .A(table_index_reg[3]),
    .B(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[3] ),
    .X(\$abc$1389$new_n107 )
  );
  sky130_fd_sc_hd__o22ai_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1420  (
    .A1(table_index_reg[8]),
    .A2(\$abc$1389$new_n79 ),
    .B1(\$abc$1389$new_n83 ),
    .B2(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[4] ),
    .Y(\$abc$1389$new_n108 )
  );
  sky130_fd_sc_hd__nor4_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1421  (
    .A(\$abc$1389$new_n105 ),
    .B(\$abc$1389$new_n106 ),
    .C(\$abc$1389$new_n107 ),
    .D(\$abc$1389$new_n108 ),
    .Y(\$abc$1389$new_n109 )
  );
  sky130_fd_sc_hd__a222oi_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1422  (
    .A1(table_index_reg[8]),
    .A2(\$abc$1389$new_n79 ),
    .B1(table_index_reg[5]),
    .B2(\$abc$1389$new_n82 ),
    .C1(\$abc$1389$new_n86 ),
    .C2(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[9] ),
    .Y(\$abc$1389$new_n110 )
  );
  sky130_fd_sc_hd__o2bb2ai_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1423  (
    .A1_N(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[4] ),
    .A2_N(\$abc$1389$new_n83 ),
    .B1(\$abc$1389$new_n82 ),
    .B2(table_index_reg[5]),
    .Y(\$abc$1389$new_n111 )
  );
  sky130_fd_sc_hd__a221oi_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1424  (
    .A1(table_index_reg[2]),
    .A2(\$abc$1389$new_n84 ),
    .B1(table_index_reg[9]),
    .B2(\$abc$1389$new_n87 ),
    .C1(\$abc$1389$new_n111 ),
    .Y(\$abc$1389$new_n112 )
  );
  sky130_fd_sc_hd__and4_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1425  (
    .A(\$abc$1389$new_n104 ),
    .B(\$abc$1389$new_n109 ),
    .C(\$abc$1389$new_n110 ),
    .D(\$abc$1389$new_n112 ),
    .X(\$abc$1389$auto$rtlil.cc:3314:And$109 )
  );
  sky130_fd_sc_hd__o21ai_0 \$abc$1389$auto$blifparse.cc:397:parse_blif$1426  (
    .A1(GHR[9]),
    .A2(PC[9]),
    .B1(rst),
    .Y(\$abc$1389$new_n114 )
  );
  sky130_fd_sc_hd__a21oi_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1427  (
    .A1(GHR[9]),
    .A2(PC[9]),
    .B1(\$abc$1389$new_n114 ),
    .Y(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_ADDR[9:0]$5 [9])
  );
  sky130_fd_sc_hd__and2_0 \$abc$1389$auto$blifparse.cc:397:parse_blif$1428  (
    .A(rst),
    .B(pred_reg),
    .X(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1384 )
  );
  sky130_fd_sc_hd__mux4_2 \$abc$1389$auto$blifparse.cc:397:parse_blif$1429  (
    .A0(\$abc$1389$auto$mem.cc:1185:emulate_transparency$107[4] ),
    .A1(\$abc$1389$auto$mem.cc:1185:emulate_transparency$107[5] ),
    .A2(\$abc$1389$auto$mem.cc:1185:emulate_transparency$107[6] ),
    .A3(\$abc$1389$auto$mem.cc:1185:emulate_transparency$107[7] ),
    .S0(table_index_reg[0]),
    .S1(table_index_reg[1]),
    .X(\$abc$1389$new_n117 )
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1430  (
    .A(table_index_reg[2]),
    .SLEEP(\$abc$1389$new_n117 ),
    .X(\$abc$1389$new_n118 )
  );
  sky130_fd_sc_hd__mux2_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1431  (
    .A0(\$abc$1389$auto$mem.cc:1185:emulate_transparency$107[2] ),
    .A1(\$abc$1389$auto$mem.cc:1185:emulate_transparency$107[3] ),
    .S(table_index_reg[0]),
    .X(\$abc$1389$new_n119 )
  );
  sky130_fd_sc_hd__a21oi_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1432  (
    .A1(table_index_reg[1]),
    .A2(\$abc$1389$new_n119 ),
    .B1(table_index_reg[2]),
    .Y(\$abc$1389$new_n120 )
  );
  sky130_fd_sc_hd__nor3_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1433  (
    .A(\$abc$1389$auto$mem.cc:1195:emulate_transparency$110 ),
    .B(\$abc$1389$new_n118 ),
    .C(\$abc$1389$new_n120 ),
    .Y(\$abc$1389$new_n121 )
  );
  sky130_fd_sc_hd__mux4_2 \$abc$1389$auto$blifparse.cc:397:parse_blif$1434  (
    .A0(\$abc$1389$auto$mem.cc:1185:emulate_transparency$107[0] ),
    .A1(\$abc$1389$auto$mem.cc:1168:emulate_transparency$103[0] ),
    .A2(\$abc$1389$auto$mem.cc:1185:emulate_transparency$107[1] ),
    .A3(\$abc$1389$auto$mem.cc:1168:emulate_transparency$103[1] ),
    .S0(\$abc$1389$auto$mem.cc:1195:emulate_transparency$110 ),
    .S1(table_index_reg[0]),
    .X(\$abc$1389$new_n122 )
  );
  sky130_fd_sc_hd__nor3b_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1435  (
    .A(table_index_reg[1]),
    .B(table_index_reg[2]),
    .C_N(\$abc$1389$new_n122 ),
    .Y(\$abc$1389$new_n123 )
  );
  sky130_fd_sc_hd__o21a_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1436  (
    .A1(\$abc$1389$new_n121 ),
    .A2(\$abc$1389$new_n123 ),
    .B1(\$abc$1389$auto$mem.cc:1541:emulate_reset$99 ),
    .X(\$shiftx$pipelined_ext/branch_gshare/branch_gshare.sv:94$15.Y )
  );
  sky130_fd_sc_hd__and2_0 \$abc$1389$auto$blifparse.cc:397:parse_blif$1438  (
    .A(PC[6]),
    .B(rst),
    .X(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1368 )
  );
  sky130_fd_sc_hd__and2_0 \$abc$1389$auto$blifparse.cc:397:parse_blif$1439  (
    .A(rst),
    .B(PC[5]),
    .X(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1370 )
  );
  sky130_fd_sc_hd__and2_0 \$abc$1389$auto$blifparse.cc:397:parse_blif$1440  (
    .A(rst),
    .B(PC[4]),
    .X(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1372 )
  );
  sky130_fd_sc_hd__and2_0 \$abc$1389$auto$blifparse.cc:397:parse_blif$1441  (
    .A(rst),
    .B(PC[3]),
    .X(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1374 )
  );
  sky130_fd_sc_hd__and2_0 \$abc$1389$auto$blifparse.cc:397:parse_blif$1442  (
    .A(rst),
    .B(PC[2]),
    .X(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1376 )
  );
  sky130_fd_sc_hd__and2_0 \$abc$1389$auto$blifparse.cc:397:parse_blif$1443  (
    .A(rst),
    .B(PC[1]),
    .X(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1378 )
  );
  sky130_fd_sc_hd__and2_0 \$abc$1389$auto$blifparse.cc:397:parse_blif$1444  (
    .A(rst),
    .B(PC[0]),
    .X(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1380 )
  );
  sky130_fd_sc_hd__and2_0 \$abc$1389$auto$blifparse.cc:397:parse_blif$1445  (
    .A(rst),
    .B(PC[7]),
    .X(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_ADDR[9:0]$5 [7])
  );
  sky130_fd_sc_hd__buf_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1446  (
    .A(rst),
    .X(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1382 )
  );
  sky130_fd_sc_hd__and2_0 \$abc$1389$auto$blifparse.cc:397:parse_blif$1447  (
    .A(rst),
    .B(PC[8]),
    .X(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_ADDR[9:0]$5 [8])
  );
  sky130_fd_sc_hd__a21oi_1 \$abc$1389$auto$blifparse.cc:397:parse_blif$1448  (
    .A1(GHR[9]),
    .A2(PC[9]),
    .B1(\$abc$1389$new_n114 ),
    .Y(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1386 )
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$196  (
    .CLK(clk),
    .D(\$abc$1389$auto$rtlil.cc:3314:And$109 ),
    .Q(\$abc$1389$auto$mem.cc:1195:emulate_transparency$110 )
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$227  (
    .CLK(clk),
    .D(\$auto$mem.cc:1642:emulate_read_first$93 [0]),
    .Q(\$abc$1389$auto$mem.cc:1168:emulate_transparency$103[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$228  (
    .CLK(clk),
    .D(\$auto$mem.cc:1642:emulate_read_first$93 [1]),
    .Q(\$abc$1389$auto$mem.cc:1168:emulate_transparency$103[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$243  (
    .CLK(clk),
    .D(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1382 ),
    .Q(\$abc$1389$auto$mem.cc:1541:emulate_reset$99 )
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$244  (
    .CLK(clk),
    .D(rst),
    .Q(\$abc$1389$auto$mem.cc:1645:emulate_read_first$95 )
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$245  (
    .CLK(clk),
    .D(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_ADDR[9:0]$5 [0]),
    .Q(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$246  (
    .CLK(clk),
    .D(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_ADDR[9:0]$5 [1]),
    .Q(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$247  (
    .CLK(clk),
    .D(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_ADDR[9:0]$5 [2]),
    .Q(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$248  (
    .CLK(clk),
    .D(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_ADDR[9:0]$5 [3]),
    .Q(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[3] )
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$249  (
    .CLK(clk),
    .D(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_ADDR[9:0]$5 [4]),
    .Q(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[4] )
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$250  (
    .CLK(clk),
    .D(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_ADDR[9:0]$5 [5]),
    .Q(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[5] )
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$251  (
    .CLK(clk),
    .D(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_ADDR[9:0]$5 [6]),
    .Q(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[6] )
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$252  (
    .CLK(clk),
    .D(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_ADDR[9:0]$5 [7]),
    .Q(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[7] )
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$253  (
    .CLK(clk),
    .D(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_ADDR[9:0]$5 [8]),
    .Q(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[8] )
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$254  (
    .CLK(clk),
    .D(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_ADDR[9:0]$5 [9]),
    .Q(\$abc$1389$auto$mem.cc:1643:emulate_read_first$94[9] )
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$255  (
    .CLK(clk),
    .D(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_DATA[7:0]$6 [0]),
    .Q(\$auto$mem.cc:1642:emulate_read_first$93 [0])
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$256  (
    .CLK(clk),
    .D(\$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_DATA[7:0]$6 [1]),
    .Q(\$auto$mem.cc:1642:emulate_read_first$93 [1])
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$264  (
    .CLK(clk),
    .D(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1384 ),
    .Q(GHR[9])
  );
  sky130_fd_sc_hd__edfxtp_1 \$auto$ff.cc:337:slice$265  (
    .CLK(clk),
    .D(\$shiftx$pipelined_ext/branch_gshare/branch_gshare.sv:94$15.Y ),
    .DE(rst),
    .Q(next_path[0])
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$266  (
    .CLK(clk),
    .D(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1380 ),
    .Q(table_index_reg[0])
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$267  (
    .CLK(clk),
    .D(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1378 ),
    .Q(table_index_reg[1])
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$268  (
    .CLK(clk),
    .D(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1376 ),
    .Q(table_index_reg[2])
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$269  (
    .CLK(clk),
    .D(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1374 ),
    .Q(table_index_reg[3])
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$270  (
    .CLK(clk),
    .D(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1372 ),
    .Q(table_index_reg[4])
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$271  (
    .CLK(clk),
    .D(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1370 ),
    .Q(table_index_reg[5])
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$272  (
    .CLK(clk),
    .D(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1368 ),
    .Q(table_index_reg[6])
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$273  (
    .CLK(clk),
    .D(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1366 ),
    .Q(table_index_reg[7])
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$274  (
    .CLK(clk),
    .D(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1364 ),
    .Q(table_index_reg[8])
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$275  (
    .CLK(clk),
    .D(\$abc$1389$auto$rtlil.cc:3513:MuxGate$1386 ),
    .Q(table_index_reg[9])
  );
  sky130_fd_sc_hd__dfxtp_1 \$auto$ff.cc:337:slice$276  (
    .CLK(clk),
    .D(1'h0),
    .Q(pred_reg)
  );
  sky130_sram_1kbyte_1rw1r_8x1024_8 \PHT.0.0.sram  (
    .addr0({ \$abc$1389$auto$mem.cc:1643:emulate_read_first$94[9] , \$abc$1389$auto$mem.cc:1643:emulate_read_first$94[8] , \$abc$1389$auto$mem.cc:1643:emulate_read_first$94[7] , \$abc$1389$auto$mem.cc:1643:emulate_read_first$94[6] , \$abc$1389$auto$mem.cc:1643:emulate_read_first$94[5] , \$abc$1389$auto$mem.cc:1643:emulate_read_first$94[4] , \$abc$1389$auto$mem.cc:1643:emulate_read_first$94[3] , \$abc$1389$auto$mem.cc:1643:emulate_read_first$94[2] , \$abc$1389$auto$mem.cc:1643:emulate_read_first$94[1] , \$abc$1389$auto$mem.cc:1643:emulate_read_first$94[0]  }),
    .addr1(table_index_reg),
    .clk0(clk),
    .clk1(clk),
    .csb0(1'h0),
    .csb1(1'h0),
    .din0({ 6'h00, \$auto$mem.cc:1642:emulate_read_first$93 [1:0] }),
    .dout0(\$auto$memory_libmap.cc:1986:emit_port$113 ),
    .dout1({ \$abc$1389$auto$mem.cc:1185:emulate_transparency$107[7] , \$abc$1389$auto$mem.cc:1185:emulate_transparency$107[6] , \$abc$1389$auto$mem.cc:1185:emulate_transparency$107[5] , \$abc$1389$auto$mem.cc:1185:emulate_transparency$107[4] , \$abc$1389$auto$mem.cc:1185:emulate_transparency$107[3] , \$abc$1389$auto$mem.cc:1185:emulate_transparency$107[2] , \$abc$1389$auto$mem.cc:1185:emulate_transparency$107[1] , \$abc$1389$auto$mem.cc:1185:emulate_transparency$107[0]  }),
    .web0(\$abc$1389$techmap\PHT.0.0.$not$memory_map.v:20$116_Y ),
    .wmask0(1'h1)
  );
  assign \$auto$mem.cc:1642:emulate_read_first$93 [7:2] = 6'h00;
  assign \$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_DATA[7:0]$6 [7:3] = { \$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_DATA[7:0]$6 [2], \$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_DATA[7:0]$6 [2], \$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_DATA[7:0]$6 [2], \$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_DATA[7:0]$6 [2], \$0$memwr$\PHT$pipelined_ext/branch_gshare/branch_gshare.sv:89$1_DATA[7:0]$6 [2] };
  assign table_index[8:0] = PC[8:0];
  assign next_path[7:1] = 7'h00;
  assign GHR_comb = { pred_reg, 9'h000 };
  assign GHR[8:0] = 9'h000;
  assign pred = pred_reg;
endmodule
